---
title: "Lab6"
author: "Marcos Bernier"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Task 1

```{r}
getwd()
```


## Task 2

```{r}
matrix1 = matrix(c(1,2,3,4),2,2,TRUE)

layout(matrix1, c(2,2),c(2,2))

curve(dnorm(x,10,4),xlim=c(10-(12),10+(12)))
curve(dnorm(x,10,2),xlim=c(10-6,10+(6)))
curve(dnorm(x,5,10),xlim=c(5-(30),5+(30)))
curve(dnorm(x,5,.5),xlim=c(5-(3*.5),5+(3*.5)))
```

```{r}
m1=0 
m2=4 
m3=10
m4=-2
s1=1
s2=2
s3=4
s4=.5
x1=2
x2=1
x3=-6
x4=-3
y1=0+(s1*3)
y2=4.9999999
y3=10
y4=-2         #declarations
```

```{r}
curve(dnorm(x,m1,s1),xlim =c(m1-(3*s1),m1+(3*s1)))
one = seq(x1,y1,length=1000)
two = dnorm(one,0,1)
polygon(c(x1,one,y1),c(0,two,0),col="red")
```

```{r}
curve(dnorm(x,m2,s2),xlim =c(m2-(3*s2),m2+(3*s2)))
one = seq(x2,y2,length=1000)
two = dnorm(one,m2,s2)
polygon(c(x2,one,y2),c(0,two,0),col="red")
```

```{r}
curve(dnorm(x,m3,s3),xlim =c(m3-(3*s3),m3+(3*s3)))
one = seq(x3,y3,length=1000)
two = dnorm(one,m3,s3)
polygon(c(x3,one,y3),c(0,two,0),col="red")
```
```{r}
curve(dnorm(x,m4,s4),xlim =c(m4-(3*s4),m3+(3*s4)))
one = seq(x4,y4,length=1000)
two = dnorm(one,m4,s4)
polygon(c(x4,one,y4),c(0,two,0),col="red")
```


## Task 3

```{r}
#gamma1 = dgamma(x,1,1)
#gamma2 = dgamma(x,3,1)
#gamma3 = dgamma(x,5,1)

curve(dgamma(x,1,1),xlim=c(0,10),ylim=c(0,1))
curve(dgamma(x,3,1),xlim=c(0,10),ylim=c(0,1),add=TRUE)
curve(dgamma(x,5,1),xlim=c(0,10),ylim=c(0,1),add=TRUE)

```

```{r}
curve(dgamma(x,shape=3,scale=2),xlim=c(0,10),ylim=c(0,1))

polygon(c(2,seq(2,5, length=10000),5),c(0,dgamma(seq(2,5, length=10000),shape =3,scale=2),0),col="orange")


curve(dgamma(x,shape=6,scale=3),xlim=c(0,10),ylim=c(0,.05))

polygon(c(1,seq(1,4, length=10000),4),c(0,dgamma(seq(1,4, length=10000),shape=6,scale=3),0),col="orange")


curve(dgamma(x,shape=2,scale=4),xlim=c(0,10),ylim=c(0,.05))

polygon(c(3,seq(3,6, length=10000),6),c(0,dgamma(seq(3,6, length=10000),shape=2,scale=4),0),col="orange")

```

## Task 4

```{r}
layout(matrix(c(1,2,3,4),2,2,TRUE),c(2,2),c(2,2))

curve(dchisq(x,1),xlim=c(0,10),ylim=c(0,1))

curve(dchisq(x,2),xlim=c(0,10),ylim=c(0,1))
curve(dchisq(x,4),xlim=c(0,10),ylim=c(0,1))
curve(dchisq(x,20),xlim=c(0,10),ylim=c(0,1))


```

```{r}
curve(dchisq(x,2),xlim=c(0,10),ylim=c(0,1))
polygon(c(2,seq(2,4,length=1000),4),c(0,dchisq(seq(2,4,length=1000),2),0),col = "red")


curve(dchisq(x,3),xlim=c(0,10),ylim=c(0,1))
polygon(c(3,seq(3,5,length=1000),5),c(0,dchisq(seq(3,5,length=1000),3),0),col = "red")

curve(dchisq(x,20),xlim=c(4,25),ylim=c(0,.3))
polygon(c(10,seq(10,21,length=1000),21),c(0,dchisq(seq(10,21,length=1000),20),0),col = "red")
```


## Task 5

```{r}
layout(matrix(c(1,2,3,4),2,2,TRUE))

curve(dweibull(x,1,11),xlim=c(0,10),ylim=c(0,1))
curve(dweibull(x,2,22),xlim=c(0,10),ylim=c(0,1))
curve(dweibull(x,3,33),xlim=c(0,10),ylim=c(0,1))
curve(dweibull(x,4,44),xlim=c(0,10),ylim=c(0,1))

```
```{r}
curve(dweibull(x,1,1),xlim=c(0,10),ylim=c(0,1))

polygon(c(3,seq(3,1000),21),c(0,dweibull(seq(3,1000),1,1),0),col="Red")


curve(dweibull(x,2,4),xlim=c(0,10),ylim=c(0,1))
polygon(c(0,seq(1,1000),10),c(0,dweibull(seq(1,1000),2,4),0),col="Red")

curve(dweibull(x,6,7),xlim=c(0,10),ylim=c(0,1))
polygon(c(0,seq(1,1000),10),c(0,dweibull(seq(1,1000),6,7),0),col="Red")

```

## Task 6

```{r}
layout(matrix(c(1, 2, 3, 4),2,2,TRUE),heights = c(2, 2),widths = c(2, 2))
xlimiter = c(0,1)
curve(dbeta(x,shape1 = 1, shape2 = 2),xlim=xlimiter)
curve(dbeta(x,shape1 = 2, shape2 = 3),xlim=xlimiter)
curve(dbeta(x,shape1 = 3, shape2 = 4),xlim=xlimiter)
curve(dbeta(x,shape1 = 5, shape2 = 6),xlim=xlimiter)
```
```{r}
curve(dbeta(x,shape1 = 1, shape2 = 2),xlim=xlimiter)

```

## Task 7

```{r}
migente <- function(y)
{
  if(y<0) return(0)
  if(y>=0 & y<= 2) return(1/8*y^3)
  if(y>2) return (1)
}

migente(-1)
```
