---
title: "Lab5"
author: "Marcos Bernier"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 1

```{r}
getwd()
```

## Task 2
```{r}
mybin=function(iter,n, p){ 
# make a matrix to hold the samples
#initially filled with NA's
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes in each trial
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(c(1,0),n,replace=TRUE, prob=c(p,1-p))
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportions
barplot(succ.tab/(iter), col=rainbow(n+1), main="Binomial simulation", xlab="Number of successes")
succ.tab/iter
}
mybin(100,10,0.7)
dbinom(100,10,0.7)
mybin(200,10,0.7)
dbinom(200,10,0.7)
mybin(500,10,0.7)
dbinom(500,10,0.7)
mybin(1000,10,0.7)
dbinom(1000,10,0.7)
mybin(10000,10,0.7)
dbinom(10000,10,0.7)
```
```{r}
dbinom(0:10, size = 10, prob = 0.7)
```

## Task 3
```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0),replace = FALSE, size =5, prob = NULL)
```

```{r}
sample(c(1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0),replace = TRUE, size =5, prob = NULL)
```

```{r}
myhyper=function(iter=100,N=20,r=12,n=5){
# make a matrix to hold the samples
#initially filled with NA's
sam.mat=matrix(NA,nr=n,nc=iter, byrow=TRUE)
#Make a vector to hold the number of successes over the trials
succ=c()
for( i in 1:iter){
#Fill each column with a new sample
sam.mat[,i]=sample(rep(c(1,0),c(r,N-r)),n,replace=FALSE)
#Calculate a statistic from the sample (this case it is the sum)
succ[i]=sum(sam.mat[,i])
}
#Make a table of successes
succ.tab=table(factor(succ,levels=0:n))
#Make a barplot of the proportions
barplot(succ.tab/(iter), col=rainbow(n+1), main="HYPERGEOMETRIC simulation", xlab="Number of successes")
succ.tab/iter
}

myhyper(100,20,12,5)
myhyper(200,20,12,5)
myhyper(500,20,12,5)
myhyper(1000,20,12,5)
myhyper(10000,20,12,5)

```

```{r}
dhyper(0:5,12,8,5)
```


## Task 4
The function creates (iter) samples of size n using the numbers between 1 and 10. The samples are represented by a barplot and the time parameter represents how long the program waits between each sample created.
```{r}
mysample=function(n, iter=10,time=0.5){
for( i in 1:iter){
#make a sample
s=sample(1:10,n,replace=TRUE)
# turn the sample into a factor
sf=factor(s,levels=1:10)
#make a barplot
barplot(table(sf)/n,beside=TRUE,col=rainbow(10), 
main=paste("Example sample()", " iteration ", i, " n= ", n,sep="") ,
ylim=c(0,0.2)
)

#release the table
Sys.sleep(time)
}
}

mysample(n=1000,iter=30,time=1)
```

Running the function produced a new sample and corresponding barplot every second!

## Task 5

```{r}
choose(8,4)
```

```{r}
1-ppois(3,2)
```

```{r}
choose(10-1,3-1) * 0.4 ^ 3 * 0.6 ^ (10-3)
dnbinom(10-3,3,0.4)
```

```{r}
pbinom(8,15,0.4)
```

## Task 6

```{r}
MATH4753BERN0021::mysample(1,1,1)
```

